# Generated by Django 4.1 on 2025-03-24 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='License must be in the format AAA12345', regex='^[A-Z]{3}\\d{5}$')]),
        ),
    ]
